[program:robotwin_sim_remote_lane0]
command=/bin/bash /workspace/RoboTwin_geo_sim_v1/policy/DP3/scripts/run_robotwin_sim_remote_formal_lane.sh 0
directory=/workspace/RoboTwin_geo_sim_v1
environment=PYTHON_BIN="/workspace/venvs/geo-utonia/bin/python",RUN_ROLE="remote",EPOCHS="300",BATCH_SIZE="256",TRAIN_WORKERS="1",VAL_WORKERS="1",TRAIN_PERSISTENT_WORKERS="true",VAL_PERSISTENT_WORKERS="true",PRECISION="bf16",ALLOW_TF32="true",OUTPUT_ROOT="/workspace/RoboTwin_geo_sim_v1/outputs/paper_revision/robotwin_sim_policy_beat_hammer_e300_bf16_v1"
autostart=false
autorestart=unexpected
startretries=3
stopasgroup=true
killasgroup=true
stopsignal=INT
stdout_logfile=/workspace/RoboTwin_geo_sim_v1/outputs/paper_revision/robotwin_sim_policy_beat_hammer_e300_bf16_v1/logs/remote_lane0.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=2
redirect_stderr=true

[program:robotwin_sim_remote_lane1]
command=/bin/bash /workspace/RoboTwin_geo_sim_v1/policy/DP3/scripts/run_robotwin_sim_remote_formal_lane.sh 1
directory=/workspace/RoboTwin_geo_sim_v1
environment=PYTHON_BIN="/workspace/venvs/geo-utonia/bin/python",RUN_ROLE="remote",EPOCHS="300",BATCH_SIZE="256",TRAIN_WORKERS="1",VAL_WORKERS="1",TRAIN_PERSISTENT_WORKERS="true",VAL_PERSISTENT_WORKERS="true",PRECISION="bf16",ALLOW_TF32="true",OUTPUT_ROOT="/workspace/RoboTwin_geo_sim_v1/outputs/paper_revision/robotwin_sim_policy_beat_hammer_e300_bf16_v1"
autostart=false
autorestart=unexpected
startretries=3
stopasgroup=true
killasgroup=true
stopsignal=INT
stdout_logfile=/workspace/RoboTwin_geo_sim_v1/outputs/paper_revision/robotwin_sim_policy_beat_hammer_e300_bf16_v1/logs/remote_lane1.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=2
redirect_stderr=true
