[program:hammer_slot_nce_seed20260805]
command=/bin/bash /workspace/RoboTwin_geo/policy/DP3/scripts/run_remote_hammer_loss_ablation_seed.sh 20260805 /workspace/RoboTwin_geo/outputs/paper_revision/hammer_semantic_loss_ablation_remote_seed20260805_e4000_20260806
directory=/workspace/RoboTwin_geo
environment=FAST_PATH="1",VARIANTS="no_ce",EPOCHS="1750",RUN_NAME_EPOCH_TAG="4000",BATCH_SIZE="6",NUM_WORKERS="8"
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:hammer_slot_nce_seed20260806]
command=/bin/bash /workspace/RoboTwin_geo/policy/DP3/scripts/run_remote_hammer_loss_ablation_seed.sh 20260806 /workspace/RoboTwin_geo/outputs/paper_revision/hammer_semantic_loss_ablation_remote_seed20260806_e4000_20260806
directory=/workspace/RoboTwin_geo
environment=FAST_PATH="1",VARIANTS="no_ce",EPOCHS="1750",RUN_NAME_EPOCH_TAG="4000",BATCH_SIZE="6",NUM_WORKERS="8"
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:hammer_slot_nsup_seed20260805]
command=/bin/bash /workspace/RoboTwin_geo/policy/DP3/scripts/run_remote_hammer_loss_ablation_seed.sh 20260805 /workspace/RoboTwin_geo/outputs/paper_revision/hammer_semantic_loss_ablation_remote_seed20260805_e4000_20260806
directory=/workspace/RoboTwin_geo
environment=FAST_PATH="1",VARIANTS="no_supcon",EPOCHS="1750",RUN_NAME_EPOCH_TAG="4000",BATCH_SIZE="6",NUM_WORKERS="8"
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:hammer_slot_nsup_seed20260806]
command=/bin/bash /workspace/RoboTwin_geo/policy/DP3/scripts/run_remote_hammer_loss_ablation_seed.sh 20260806 /workspace/RoboTwin_geo/outputs/paper_revision/hammer_semantic_loss_ablation_remote_seed20260806_e4000_20260806
directory=/workspace/RoboTwin_geo
environment=FAST_PATH="1",VARIANTS="no_supcon",EPOCHS="1750",RUN_NAME_EPOCH_TAG="4000",BATCH_SIZE="6",NUM_WORKERS="8"
autostart=false
autorestart=false
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
