#!/usr/bin/env python3
"""Keep only expert-labeled rows after an admitted on-policy handoff.

The collector can retain a policy prefix so that the expert starts from the
exact deployed state.  Those prefix actions are generated by the policy and
must not be treated as expert targets.  This selector uses the collection
manifest solely to identify the first expert-labeled frame and retains the
complete continuation through successful release/settling.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def select_rows(
    payload: dict[str, np.ndarray], records: list[dict]
) -> tuple[dict[str, np.ndarray], dict[str, dict]]:
    sample_count = len(payload["episode_id"])
    keep = np.zeros(sample_count, dtype=bool)
    summary: dict[str, dict] = {}
    record_by_episode = {int(record["episode"]): record for record in records}
    for episode in np.unique(payload["episode_id"]):
        episode = int(episode)
        if episode not in record_by_episode:
            raise KeyError(f"manifest lacks admitted episode {episode}")
        record = record_by_episode[episode]
        if not bool(record.get("recovered", False)):
            raise ValueError(f"episode {episode} is not an admitted recovery")
        handoff_frame = int(record["policy_controls"])
        selected = (payload["episode_id"] == episode) & (
            payload["frame_index"] >= handoff_frame
        )
        if not selected.any():
            raise RuntimeError(
                f"episode {episode} has no rows at/after handoff {handoff_frame}"
            )
        keep |= selected
        summary[str(episode)] = {
            "handoff_frame": handoff_frame,
            "first_kept_frame": int(payload["frame_index"][selected].min()),
            "last_kept_frame": int(payload["frame_index"][selected].max()),
            "kept_samples": int(selected.sum()),
            "expert_continuation": str(record["expert_continuation"]),
        }
    output = {
        key: (value[keep] if value.ndim > 0 and len(value) == sample_count else value)
        for key, value in payload.items()
    }
    return output, summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    if args.output.exists() and not args.overwrite:
        raise FileExistsError(args.output)
    with np.load(args.input, allow_pickle=False) as archive:
        payload = {key: np.asarray(archive[key]) for key in archive.files}
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    output, summary = select_rows(payload, manifest["records"])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.output, **output)
    metadata = {
        "schema_version": 1,
        "input": str(args.input.resolve()),
        "manifest": str(args.manifest.resolve()),
        "output": str(args.output.resolve()),
        "input_samples": int(len(payload["episode_id"])),
        "kept_samples": int(len(output["episode_id"])),
        "episodes": summary,
        "policy_prefix_used_as_supervision": False,
        "deployment_change": False,
    }
    args.output.with_suffix(".json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(metadata, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
