#!/bin/bash

_robotwin_data_paths_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROBOTWIN_REPO_ROOT=$(cd "${_robotwin_data_paths_dir}/.." && pwd)
ROBOTWIN_SERVER_STORAGE_ROOT=${ROBOTWIN_SERVER_STORAGE_ROOT:-/shared2/sz}
ROBOTWIN_SERVER_DATA_ROOT=${ROBOTWIN_SERVER_DATA_ROOT:-${ROBOTWIN_SERVER_STORAGE_ROOT}/robotwin_data}
ROBOTWIN_SERVER_RAW_DATA_ROOT=${ROBOTWIN_SERVER_RAW_DATA_ROOT:-${ROBOTWIN_SERVER_DATA_ROOT}/data}

if [ -d "${ROBOTWIN_SERVER_RAW_DATA_ROOT}" ]; then
    ROBOTWIN_STORAGE_MODE=server
    ROBOTWIN_RAW_DATA_ROOT=${ROBOTWIN_RAW_DATA_ROOT:-${ROBOTWIN_SERVER_RAW_DATA_ROOT}}
    ROBOTWIN_DP3_DATA_ROOT=${ROBOTWIN_DP3_DATA_ROOT:-${ROBOTWIN_SERVER_DATA_ROOT}/policy/DP3/data}
else
    ROBOTWIN_STORAGE_MODE=local
    ROBOTWIN_RAW_DATA_ROOT=${ROBOTWIN_RAW_DATA_ROOT:-${ROBOTWIN_REPO_ROOT}/data}
    ROBOTWIN_DP3_DATA_ROOT=${ROBOTWIN_DP3_DATA_ROOT:-${ROBOTWIN_REPO_ROOT}/policy/DP3/data}
fi

export ROBOTWIN_REPO_ROOT
export ROBOTWIN_SERVER_STORAGE_ROOT
export ROBOTWIN_SERVER_DATA_ROOT
export ROBOTWIN_SERVER_RAW_DATA_ROOT
export ROBOTWIN_STORAGE_MODE
export ROBOTWIN_RAW_DATA_ROOT
export ROBOTWIN_DP3_DATA_ROOT

unset _robotwin_data_paths_dir
